export const pizzas = [
  {
    id: "1",
    name: "CHICKEN BBQ",
    price: 6990,
    ingredients: [
      "Base de salsa BBQ",
      "pollo",
      "cebolla morada",
      "tocino",
      "mozzarella",
    ],
    img: "https://nuevo.meltpizzas.com/media/catalog/product/c/h/chicken_bbq_1_2.jpg",
  },
  {
    id: "2",
    name: "ESPAÑOLAZA",
    price: 8990,
    ingredients: [
      "Chorizo",
      "tomate",
      "pimentón",
      "aceitunas negras",
      "jamón ahumado",
    ],
    img: "https://lucasi.cl/wp-content/uploads/2020/02/pizza_espanola_chiguayante_lucasi.jpg",
  },
  {
    id: "3",
    name: "PESTO MARGARITA",
    price: 7500,
    ingredients: [
      "Doble tomate cherry",
      "doble mozzarella",
      "shot de pesto",
      "orégano",
    ],
    img: "https://nuevo.meltpizzas.com/media/catalog/product/p/e/pestomargarita_sin-sello_1portada.jpg",
  },
  {
    id: "4",
    name: "TODAS LAS CARNES",
    price: 10000,
    ingredients: [
      "Pepperoni",
      "jamón",
      "carne mechada",
      "tocino",
      "mozzarella",
    ],
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ3Sc_SgxBUibkggW4simqWD3bZa9EwRhqrQ&s",
  },
  {
    id: "5",
    name: "JAMÓN SERRANO RÚCULA",
    price: 12000,
    ingredients: [
      "Jamón serrano",
      "rúcula fresca",
      "queso mozzarella",
      "shot de aceite de oliva",
    ],
    img: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhoZDEWMYSB7BRvd7irMYB7ZWwbDFyoFeMx_8OZ8nBQAZW0wywm-Pa7za1gdHVFczgR0-mkmZRRdRi5RynZMP8p2_4zozqFs7JTJQNLw-UHUgrAvl7V2myaDiK9jY6dsjjs8q6DE63qF1Y/s1600/pizza-jamon-rucula-queso-01b.jpg",
  },
  {
    id: "6",
    name: "MEATCHADA",
    price: 11500,
    ingredients: ["Carne mechada", "tomate", "cebolla morada", "mozzarella"],
    img: "https://furano.cl/tienda/15-large_default/pizza-mechada.jpg",
  },
];
